### ISSUE TITLE
Very very high ram usage

### ISSUE THREAD

**Issue by ghost** [blay09/BetterMinecraftChat#64]
This is a chat mod which should not be using close to as much ram as it just did, it used almost 2gb itself when running this and made my computer crash. I am not the only one who is having this issue. A streamer I watch is having this same issue. I only installed it to see if I had the same issue and it did. This is with the latest build of chattweaks for 1.12.2 I have no other chat mods installed either. So it shouldn't be clashing with anything. I cannot give the log because it crashed before it could be created. I will add it was with a very light mod pack also, (Just another skyblock JASB) If you want to check if anything in that modpack has another mod that clashes. Wish I could provide more details but at the moment I cannot.

**Comment by kingerking** [comment]
This is happening too me as well. literally got the same numbers

**Comment by BlayTheNinth** [comment]
As a quick first solution you can disable `Twitch Subscriber Emotes` in the config.

```
emotes {
    B:"Twitch Subscriber Emotes"=false
}
```

This is happening because Twitch rolled out the affiliate program and there's a lot of new channel emotes now (totalling up to 1.1 million emotes). Chat Tweaks doesn't load the image until it's needed, but it does store the emote code and some metadata, which adds up.

To resolve this,
- subscriber emotes will no longer be enabled by default and will have a warning in their config description
- the amount of stored metadata (especially parts that were duplicates) will be reduced to a minimum and instead computed when needed
- emotes of channels with less than five emotes will be ignored
